---

- hosts: all
  become: true
  tasks:

  - name: install apache and php 
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
  - name: copy default html file for site
    tags: apache,apache2,ubuntu
    copy:
      src: default_site.html
      dst: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    


